# Nombre del entorno Conda basado en el nombre del proyecto
name: {{ cookiecutter.project_slug }}

# Canales desde los cuales instalar paquetes
channels:
  - anaconda
  - conda-forge
  - defaults

dependencies:
  # Dependencias básicas para la automatización
  {% if cookiecutter.project_packages == "All" -%}
  - fs
  - jupyter
  - jupyterlab
  - pathlib
  {% endif -%}
  
  # Sección para instalar paquetes desde pip
  - pip
  {% if cookiecutter.project_packages == "All" -%}
  - pyprojroot
  {% endif -%}
  
  # Especificación de la versión de Python
  - python={{ cookiecutter.python_version }}
  
  # Paquetes adicionales instalados a través de pip
  - pip:
    {% if cookiecutter.project_packages == "All" -%}
    - pyhere
    {% endif -%}
